### ISSUE TITLE
Redirect http -> https

### ISSUE THREAD

**Issue by robinbowes** [doingcloudright/airship.tf#1]
Hitting http://airship.tf should re-direct to https://airship.tf, IMO.

**Comment by maartenvanderhoef** [comment]
Just enabled it with github pages, should be there shortly. Thanks for helping!

**Comment by robinbowes** [comment]
Yes, I hope it came across as helpful - looks an interesting project :)

Expect PRs...

**Comment by maartenvanderhoef** [comment]
Come join the #airship channel on Slack, or the still very empty Gitter. Looking forward to discuss your ideas :-)
